### ISSUE TITLE
cuckoo cant start after installing

### ISSUE THREAD

**Issue by maltcev0i** [cert-ee/cuckoo3#16]
ERROR [cuckoo.common.log]: Failure during Cuckoo startup: Failed to load config file /home/cuckoosb/.cuckoocwd/conf/web/web.yaml. Error in config file: /home/cuckoosb/.cuckoocwd/conf/web/web.yaml. Missing required key user

**.cuckoocwd/conf/web/web.yaml**
```
# Remote storage usage is the retrieval of analysis reports etc from
# a remote Cuckoo 'long term storage' host.
remote_storage:
  enabled: False
  api_url: Null

  # API key does not need administrator privileges
  api_key: Null

elasticsearch:
  # The Elasticsearch settings must be configured to be able to use any of
  # the features in this section.

  # Enable or disable the Cuckoo web results search functionality
  web_search:
    enabled: False

  # Enable or disable Cuckoo web results statistics. Detected family, behavior
  # graphs, amount of submissions, etc.
  statistics:
    enabled: False

    # All enabled charts types and the time ranges over which they
    # should display data. Available range: daily, weekly, monthly, yearly.
    # Available chart examples: families_bar, families_line, targettypes_bar,
    # categories_bar, categories_line, submissions_line
    charts:
    - chart_type: submissions_line
      time_range: yearly
    - chart_type: submissions_line
      time_range: monthly
    - chart_type: families_bar
      time_range: weekly
    - chart_type: families_line
      time_range: weekly
    - chart_type: targettypes_bar
      time_range: monthly
    - chart_type: categories_bar
      time_range: monthly

  # The Elasticsearch hosts where results are reported to during processing.
  # Should be one ore more host:port combinations.
  hosts:
    - http://127.0.0.1:9200

  indices:
    # The names to use when searching Elasticsearch. Each name must be unique
    # and should also be used in reporting.
    names:
      analyses: analyses
      tasks: tasks
      events: events

  # The max result window that will be used in searches. The Elasticsearch default is 10000. This
  # window has impact in how far back you can search with queries that match a large amount of documents.
  max_result_window: 10000

# Specific web features that can be disabled/enabled
web:
  downloads:
    # Enable/disable submitted file downloading.
    submitted_file: Null
    # A list of strings representing the subnets or ipaddresses that can download
    allowed_subnets: Null
(venv) cuckoosb@perm-cuckoosb:~$ ^C
(venv) cuckoosb@perm-cuckoosb:~$ sudo nano .cuckoocwd/conf/web/web.yaml
(venv) cuckoosb@perm-cuckoosb:~$ sudo nano .cuckoocwd/conf/web/web.yaml
(venv) cuckoosb@perm-cuckoosb:~$ cat .cuckoocwd/conf/web/web.yaml
# Remote storage usage is the retrieval of analysis reports etc from
# a remote Cuckoo 'long term storage' host.
remote_storage:
  enabled: False
  api_url: Null

  # API key does not need administrator privileges
  api_key: Null

elasticsearch:
  # The Elasticsearch settings must be configured to be able to use any of
  # the features in this section.

  # Enable or disable the Cuckoo web results search functionality
  web_search:
    enabled: False

  # Enable or disable Cuckoo web results statistics. Detected family, behavior
  # graphs, amount of submissions, etc.
  statistics:
    enabled: False

    # All enabled charts types and the time ranges over which they
    # should display data. Available range: daily, weekly, monthly, yearly.
    # Available chart examples: families_bar, families_line, targettypes_bar,
    # categories_bar, categories_line, submissions_line
    charts:
    - chart_type: submissions_line
      time_range: yearly
    - chart_type: submissions_line
      time_range: monthly
    - chart_type: families_bar
      time_range: weekly
    - chart_type: families_line
      time_range: weekly
    - chart_type: targettypes_bar
      time_range: monthly
    - chart_type: categories_bar
      time_range: monthly

  # The Elasticsearch hosts where results are reported to during processing.
  # Should be one ore more host:port combinations.
  hosts:
    - http://127.0.0.1:9200

  indices:
    # The names to use when searching Elasticsearch. Each name must be unique
    # and should also be used in reporting.
    names:
      analyses: analyses
      tasks: tasks
      events: events

  # The max result window that will be used in searches. The Elasticsearch default is 10000. This
  # window has impact in how far back you can search with queries that match a large amount of documents.
  max_result_window: 10000

# Specific web features that can be disabled/enabled
web:
  downloads:
    # Enable/disable submitted file downloading.
    submitted_file: Enable
    # A list of strings representing the subnets or ipaddresses that can download
    allowed_subnets: Null

```
